name: ArmourerApi
main: tech.joaoalberis.ArmourerApi
version: 1.0.2
author: MrJoao
description: Api desenvolvida para fazer interação com o mod armourer's workshop.
commands:
  aweden:
    description: §cArmourerApi Help.